=== protreptic/UpdatingService/UpdatingService/assets/updateIndex.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="updateIndex" type="updateIndexType" />
    
   	<xs:complexType name="updateIndexType">
		<xs:sequence>
			<xs:element name="indexUrl" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="updateEntries" type="updateEntriesType" />
		</xs:sequence>   
	</xs:complexType> 
    
	<xs:complexType name="updateEntriesType">
		<xs:sequence>
			<xs:element name="updateEntry" type="updateEntryType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>   
	</xs:complexType> 
	
	<xs:complexType name="updateEntryType">
		<xs:sequence>
			<xs:element name="package" type="xs:string" nillable="false" minOccurs="1" maxOccurs="1" />
			<xs:element name="versionCode" type="xs:integer" nillable="false" minOccurs="1" maxOccurs="1" />
			<xs:element name="versionName" type="xs:string"	nillable="false" minOccurs="1" maxOccurs="1" />
			<xs:element name="applicationName" type="xs:string"	minOccurs="0" maxOccurs="1" />
			<xs:element name="description" type="xs:string"	minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== protreptic/UpdatingService/UpdatingService/assets/updateIndex.xml
<?xml version="1.0" encoding="UTF-8"?>
<updateIndex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="updateIndex.xsd">
  <indexUrl>indexUrl</indexUrl>
  <updateEntries>
    <updateEntry>
      <package>package</package>
      <versionCode>0</versionCode>
      <versionName>versionName</versionName>
      <applicationName>applicationName</applicationName>
      <description>description</description>
    </updateEntry>
  </updateEntries>
</updateIndex>
